### ISSUE TITLE
数据集需要预处理嘛？

### ISSUE THREAD

**Issue by d8899p** [MeepoAII/CCF-alzheimer-s-disease-datafountian#1]
大佬麻烦问下这个数据集需要预处理嘛？还是直接用官方下载的数据集？

**Comment by MeepoAII** [comment]
不是大佬哈，，代码里我已经读取过了，直接用就行

**Comment by d8899p** [comment]
> 不是大佬哈，，代码里我已经读取过了，直接用就行

好的，意思就说直接用官方那个数据集下载好后，直接放你项目里运行就OK了对吧？

**Comment by MeepoAII** [comment]
是滴，路径改一下就行

**Comment by d8899p** [comment]
好的多谢多谢
